name: proyect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '3.3.4'

dependencies:
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  flutter:
    sdk: flutter
  firebase_database: ^10.5.4
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
